### ISSUE TITLE
avada fatal error when used with Optimole 

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#429]
**Describe the bug**
```
Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Image optimization service by Optimole.

First, visit your website (https://<site>shop/) and check for any visible issues. Next, visit the page where the error was caught (https://<site>/shop/shop/wp-admin/admin.php?_wpnonce=dc29278955&action=fusion_trash_element&post=1044) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://<site>/shop/wp-login.php?action=enter_recovery_mode&rm_token=<site>&rm_key=<site>

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.0
Active theme: Avada Child (version 1.0.0)
Current plugin: Image optimization service by Optimole (version 3.4.3)
PHP version 7.4.29

Error Details
=============
An error of type E_ERROR was caused in line 518 of the file /home/<site>/public_html/shop/wp-content/plugins/optimole-wp/inc/manager.php. Error message: Uncaught Error: Call to a member function use_cdn() on null in /home/<site>/public_html/shop/wp-content/plugins/optimole-wp/inc/manager.php:518
Stack trace:
#0 /home/<site>/public_html/shop/wp-content/plugins/optimole-wp/inc/media_offload.php(318): Optml_Manager->extract_urls_from_content('[fusion_builder...')
#1 /home/<site>/public_html/shop/wp-includes/class-wp-hook.php(309): Optml_Media_Offload->filter_uploaded_images(Array)
#2 /home/<site>/public_html/shop/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#3 /home/<site>/public_html/shop/wp-includes/post.php(4374): apply_filters('wp_insert_post_...', Array, Array, Array, true)
#4 /home/<site>/public_html/shop/wp-includes/post.php(4775): wp_insert_post(Array, false, true)
#5 /home/<site>/public_html/shop/wp-includes/post.php(3575): wp_update_post(Array)
#6 /home/<site>/public_html/shop/wp-content/plugins/fusion-builder/inc/class-fusion-builder-library.php(867): wp_trash_post('1044')
#7 /home/b

```

**Comment by GrigoreMihai** [comment]
I was not able to replicate this, it looks it was an one time issue. The ticket is here https://secure.helpscout.net/conversation/1918606422/326063?folderId=2353201 .
